version: '3'

services:
  banque-pg:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=BanqueServiceUser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=BanqueService
    volumes:
      - ./data/banque_pg:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  data:
