version: '3'

services:
  banque-pg:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=BanqueServiceUser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=BanqueService
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  banque:
    build:
      context: ./Banque-service
    depends_on:
      - banque-pg
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BanqueService
      - SPRING_DATASOURCE_USERNAME=BanqueServiceUser
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8100:8082"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
volumes:
  data:
