spring:
  application:
    name: Gateway-bank-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
      routes:
        - id: Merchant
          uri: lb://Merchant-service/
          predicates:
            - Path=/pay/**
          filters:
            - RewritePath=/pay/(?<path>.*), /Merchant-devise/$\{path}
        - id: Banque
          uri: lb://Banque-service/
          predicates:
            - Path=/pay/**
          filters:
            - RewritePath=/pay/(?<path>.*), /$\{path}
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      config:
        enabled: false

server:
  port: 8100

